# Generated by Django 4.2.3 on 2025-01-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='Start date and time of the slot')),
                ('end_time', models.DateTimeField(help_text='End date and time of the slot')),
                ('sport_type', models.CharField(help_text='Type of sport for the slot', max_length=100)),
                ('is_booked', models.BooleanField(default=False, help_text='Whether the slot is booked')),
                ('location', models.CharField(choices=[('Pop', 'Pop'), ('Nordic', 'Nordic'), ('Ota', 'Ota')], help_text='Location of the slot', max_length=20)),
            ],
        ),
    ]
