# Generated by Django 4.2.1 on 2025-02-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_days', models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day(s) of the week when this rule applies', max_length=20)),
                ('start_time', models.TimeField(help_text='Start time of the rule')),
                ('end_time', models.TimeField(help_text='End time of the rule')),
                ('sport', models.CharField(choices=[('Padel', 'Padel'), ('Tennis', 'Tennis'), ('Squash', 'Squash'), ('Hiit', 'Hiit')], help_text='Sport for the rule', max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='end_time',
            new_name='end_datetime',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='start_time',
            new_name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='sport_type',
        ),
        migrations.AddField(
            model_name='slot',
            name='sport',
            field=models.CharField(choices=[('Padel', 'Padel'), ('Tennis', 'Tennis'), ('Squash', 'Squash'), ('Hiit', 'Hiit')], default='Padel', help_text='Sport for the slot', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slot',
            name='location',
            field=models.CharField(choices=[('Pop', 'Pop'), ('Nordic', 'Nordic'), ('Ota', 'Ota'), ('Barrys', 'Barrys')], help_text='Location of the slot', max_length=20),
        ),
    ]
