# Generated by Django 4.2.1 on 2025-02-25 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchi', '0002_slotrule_rename_end_time_slot_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='slot_rule',
            field=models.ForeignKey(help_text='Slot rule for the slot', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='matchi.slotrule'),
        ),
    ]
